import { StyleSheet } from 'react-native';

export const userScreenStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    gap: 16,
  },
  errorMessage: {
    color: '#000000',
    fontSize: 15,
    textAlign: 'center',
  },
  content: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 10,
    gap: 10,
    backgroundColor: '#FFFFFF',
  },
  profileDescription: {
    minHeight: 101,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  identity: {
    flex: 1,
    minHeight: 81,
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 2,
  },
  name: {
    color: '#000000',
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '700',
  },
  username: {
    color: '#637068',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '500',
  },
  following: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 15,
    fontWeight: '300',
    letterSpacing: 0.25,
  },
  bio: {
    color: '#14221D',
    fontSize: 13,
    lineHeight: 17,
    marginTop: 4,
  },
  outlineButton: {
    minHeight: 37,
    borderWidth: 1,
    borderColor: '#000000',
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  followButton: {
    minHeight: 38,
    borderWidth: 1,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  followActionButton: {
    backgroundColor: '#14221D',
    borderColor: '#14221D',
  },
  followActionButtonLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  unfollowButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
  },
  unfollowButtonLabel: {
    color: '#000000',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  requestedButton: {
    backgroundColor: '#F3F4F6',
    borderColor: '#D1D5DB',
  },
  requestedButtonLabel: {
    color: '#4B5563',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  pressed: { opacity: 0.55 },
  buttonLabel: {
    color: '#000000',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  statistics: { padding: 10, gap: 10 },
  statRow: { flexDirection: 'row', gap: 10 },
  statLabel: { flex: 1, color: '#000000', fontSize: 12, lineHeight: 15, fontWeight: '600' },
  statValue: { flex: 1, color: '#000000', fontSize: 12, lineHeight: 15, fontWeight: '400' },
  actions: { minHeight: 37, flexDirection: 'row', gap: 10 },
  actionButton: {
    flex: 1,
    minHeight: 37,
    borderWidth: 1,
    borderColor: '#000000',
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapSection: { padding: 10, gap: 10 },
  mapHeading: { color: '#000000', fontSize: 16, lineHeight: 19, fontWeight: '600' },
  mapEmpty: {
    width: '100%',
    height: 180,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
  },
  emptyMapText: {
    color: '#637068',
    fontSize: 13,
  },
});
