import { StyleSheet } from 'react-native';

export const rowStyles = StyleSheet.create({
  avatarContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E7EDDE',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    flexShrink: 0,
  },
  avatarImg: { width: 44, height: 44 },
  avatarInitials: { color: '#24331B', fontSize: 14, fontWeight: '700' },
  inviteActionsRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  acceptBtn: {
    backgroundColor: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  acceptBtnText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600' },
  declineBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  declineBtnText: { color: '#4B5563', fontSize: 12, fontWeight: '600' },
  acceptedBadge: {
    backgroundColor: '#DCFCE7',
    borderWidth: 1,
    borderColor: '#86EFAC',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  acceptedBadgeText: { color: '#15803D', fontSize: 12, fontWeight: '600' },
  declinedBadge: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  declinedBadgeText: { color: '#6B7280', fontSize: 12, fontWeight: '600' },
  followBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
  },
  followActiveBtn: { backgroundColor: '#000000' },
  followingBtn: { backgroundColor: '#F3F4F6', borderWidth: 1, borderColor: 'rgba(0, 0, 0, 0.1)' },
  followBtnText: { fontSize: 12, fontWeight: '600', lineHeight: 15 },
  followActiveBtnText: { color: '#FFFFFF' },
  followingBtnText: { color: '#374151' },
  pressed: { opacity: 0.6 },
});
